### ISSUE TITLE
Preprocessing of 3D assets

### ISSUE THREAD

**Issue by RuihanGao** [tyhuang0428/DreamPhysics#2]
Hi, 

Thanks for the great work!

I have questions about the 3D assets. In the provided example, `ficus` comes from a reconstructed scene of  Gaussian Splatting; what about the `ball` example? Is it some 3D asset that we can download from online resources? If so, how did you preprocess it and generate the `.ply` file with opacity and `f_dc` parameters?

**Comment by tyhuang0428** [comment]
For 3D assets like the ball, we use [LGM](https://github.com/3DTopia/LGM) to generate. The generated ply files have necessary information to be loaded by GS, although spherical harmonics are not included. Besides, the generation quality is unstable, you may also try some latest 3DGS generators if you want to get more realistic assets.

**Comment by RuihanGao** [comment]
Hi Tianyu,

Got it, thank you so much for the helpful reply and suggestions! I will give it a try.
